apiVersion: v1
kind: Service
metadata:
  name: argocd-external-service
  namespace: redayit-backend
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
  ports:
  - port: 80
